### ISSUE TITLE
TypeError: Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by emk** [jonathandturner/rls_vscode#25]
I tried to follow the setup instructions. I also set `rustup override set nightly` on both the `rls` directory and my Rust project directory.

vcscode 1.8.1, and all RLS checkouts from just a few minutes ago.

(One oddity about my system: The language is set to French, and vscode gives me some kind of cut off warning messages which might be related to missing messages. I tried re-running it English mode, but it the debugged copy of vscode doesn't honor environment variables set in the shell which launched the host vscode.)

```
/usr/share/code/code --debugBrkPluginHost=6242 --extensionDevelopmentPath=/home/emk/w/src/rust-libs/rls_vscode 
TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-languageclient/lib/main.js:647:30)
    at LanguageClient.stop (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-languageclient/lib/main.js:621:14)
    at LanguageClient.handleConnectionError (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-languageclient/lib/main.js:882:18)
    at errorHandler (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-languageclient/lib/main.js:744:19)
    at /home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-languageclient/lib/main.js:47:42
    at CallbackList.invoke (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/emk/w/src/rust-libs/rls_vscode/node_modules/vscode-jsonrpc/lib/events.js:167:36)
```

**Comment by jonathandturner** [comment]
A few things to try:

In the RLS checkout directory, do the unit tests pass?

```
RUST_TEST_THREADS=1 cargo test
```

Did you set the RLS_ROOT environment variable?  I feel like I've seen a similar issue when I forgot to set it.

**Comment by amarant** [comment]
I have the same error, the unit tests pass, I am on Ubuntu 14.04 my system is also in French, I also see the warning messages but they disappear if I launch vscode with :
`code . --locale=en`
The error is located in handleConnectionError :
> "Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at Pipe.onread (net.js:564:26)"

so its probably a crash in the RLS server, but I don't know

**Comment by jonathandturner** [comment]
We've been seeing some reports of people not having recent enough node/npm for it to work.  If it's not recent enough, people seem to have a handful of different problems.

Here are the versions I'm using:

```
jturner-23759:rack jturner$ node --version
v5.10.1
jturner-23759:rack jturner$ npm --version
3.8.3
```

**Comment by emk** [comment]
I'm running node 7, I believe. Can check tomorrow.

Le 19 janv. 2017 8:10 PM, "Jonathan Turner" <notifications@github.com> a
écrit :

**Comment by oli-obk** [comment]
I had the same issue (node 6 here).

I think it might be fixed by running `cargo build --release` in the `rls` checkout. If the issue still occurs, then that means that the project you are testing uses a different rust from the `rls` project (due to `rustup override`). A partial solution would be giving `child_process.spawn` the `rlsCargoPath` as the current directory, instead of using `--manifest-path`, by passing a third argument `{ cwd: rlsCargoPath }`. The problem of bad error reporting when `cargo run` fails is still open.

I need to run, so I can't fully test it, because `cargo build --release` takes ages.

**Comment by jonathandturner** [comment]
@oli-obk - is this still an issue?

**Comment by jonathandturner** [comment]
cc @emk ^

**Comment by oli-obk** [comment]
@jonathandturner not in the cases I mentioned. But the moment your rustc errors, e.g. because you forgot to set `rustup override set nightly` on the `rls` directory, you still get the error. We should probably catch such errors and print a real error message.

**Comment by jonathandturner** [comment]
@oli-obk - hmm, I'm not sure what that would look like since these exceptions are being thrown inside of vscode's support modules.  What did you have in mind?

**Comment by oli-obk** [comment]
revert to dumping the command line like in the debug mode? It will rarely happen, but if it happens, the verbosity isn't really relevant imo.

**Comment by nrc** [comment]
This should be fixed by an LSP update I think
