### ISSUE TITLE
Strange behaviour after VS Code hot exit

### ISSUE THREAD

**Issue by gentoo90** [jonathandturner/rls_vscode#35]
RLS VS Code doesn't work well with VS Code hot exit feature (preserving unsaved changes to files on exit).

Steps to reproduce:
1. Open a rust project in VS Code.
2. Change something in a file, for example rename a function so it's underlined as non-existant (e.g. `unwrap` -> `unwrp`).
3. Close VS Code, **do not** save the file.
4. Open the project again.

Expected result:
`unwrp` is still underlined with red.
Actual result:
`unwrp` is not underlined and hover shows the doc for `unwrap`

![rlshotexit1](https://cloud.githubusercontent.com/assets/1297574/22757745/bdbdf55e-ee54-11e6-889e-c2994423a864.png)

5. Rename it back to `unwrap`

Expected result:
No errors
Actual result:
Error: `unwraap` not found.

![rlshotexit2](https://cloud.githubusercontent.com/assets/1297574/22757864/2ac87cf0-ee55-11e6-8bb3-9ee03f6eb466.png)

Environment:
gentoo linux x64
vscode 1.9
rustc 1.16.0-nightly (eedaa94e3 2017-02-02)
rls `fb63cd5fb`
rls_vscode `12d432e3b`

**Comment by jonathandturner** [comment]
We've done a bit of work in making the RLS more resilient.  Can you test to see if this issue is still a problem?  If it is, can you reopen this issue?

**Comment by gentoo90** [comment]
Works fine now. Thanks!
