### ISSUE TITLE
Error: spawn rls ENOENT

### ISSUE THREAD

**Issue by amand1996** [jonathandturner/rls_vscode#38]
Whenever I start the extension using the debug launch extension in VS Code. The following error comes up in the debugging console. The Window shows the message "RLS status: starting up" all the time.

/usr/share/code/code --debugPluginHost=32801 --extensionDevelopmentPath=/home/aman/Desktop/rls_vscode 
Uncaught Exception:  Error: spawn rls ENOENT
Error: spawn rls ENOENT

**Comment by jonathandturner** [comment]
What version of node/npm are you running with?  Some other folks have reported similar issues, and it seems to generally be out-of-date node/npm installs or missing the RLS_ROOT step in the install.

**Comment by amand1996** [comment]
node.js version is v6.10.0
npm version 3.9.5

I have set the RLS_ROOT properly now. The error has gone away. But still it shows the same message "RLS status: starting up" all the time.

**Comment by jonathandturner** [comment]
If you've never built rls in release mode, you'll see the starting up message for a while as it builds rls.  If it doesn't go away after a few minutes, then something else probably needs to be updated.

Can you confirm that the tests in rls work correctly?

```
RUST_TEST_THREADS=1 cargo test
```

**Comment by amand1996** [comment]
Yes. All the tests passed with status ok. Maybe I should try waiting for some more time to see if the status changes. I had already built the code in the release mode using the command "cargo build --release". The way I am doing this right now is first starting the RLS using "cargo run". Then I open VS Code and start the extension. Tell me if I need not start the RLS using that cargo command?

**Comment by jonathandturner** [comment]
you don't need to start RLS, as the vscode plugin from https://github.com/jonathandturner/rls_vscode will start it for you.  In fact, starting it yourself may cause issues, I'm not 100% sure

**Comment by jonathandturner** [comment]
Also, since we're chatting, you might be interested to know that "cargo run" runs the debug version rather than the release version.

**Comment by amand1996** [comment]
Thanks for your help. I'm again trying to start it as per your instructions. Hope that works! It's taking some time. Is there any way to check if it's building the code or there's some issue. I have been waiting for a while but unable to understand whether its working or not.

**Comment by jonathandturner** [comment]
If you've already build the rls with release mode by hand, set up RLS_ROOT and connected your compiler (https://github.com/rust-lang-nursery/rls/blob/master/README.md), then the "starting up" message should go away almost immediately.

**Comment by amand1996** [comment]
Still, I'm unable to make this work. I think I'm doing something wrong in "Step 2: Connect the RLS to your compiler" of "https://github.com/rust-lang-nursery/rls/blob/master/README.md". When I run this "rustc --print sysroot" command, I get the output "/usr/local". What should be my next command? I'm on the Ubuntu 16.04 system. Also, please help me with step 3 and step 4 also. The command "rustup component add rust-analysis" doesn't work. it says "rustup: command not found", but rustc and cargo everything is installed.

**Comment by amand1996** [comment]
I have now installed rustup. So, it has started working now. But now rustc is not working. rustc and rustup are not working simultaneously. "rustc" command outsputs "command not found"

**Comment by jonathandturner** [comment]
Rustup manages the rustc installation, so if you installed rust via ubuntu or some other means, you'll want to remove the old way and just allow rustup to manage it.

**Comment by amand1996** [comment]
Ok. Now everything is working. rustc is also working. rustup is also working. i updated nodejs and npm. I also built the code. Added the root path variable too. It is showing "/usr/share/code/code --debugPluginHost=9458 --extensionDevelopmentPath=/home/aman/Desktop/rls_vscode 
Uncaught Exception:  Error: spawn rls ENOENT
Error: spawn rls ENOENT" now. If this works, everything should work fine.

**Comment by jonathandturner** [comment]
so you're still seeing "spawn rls ENOENT" after all of that?

**Comment by amand1996** [comment]
yes. :( I don't understand why it's not working out.

**Comment by jonathandturner** [comment]
when you set RLS_ROOT, did you restart vscode?

**Comment by amand1996** [comment]
Yes I did. RLS_ROOT should have the location of the rls source files, am I right?

**Comment by jonathandturner** [comment]
it should be the root of the checkout not the source files.  For me, it's:

RLS_ROOT="/Users/jturner/Source/rls"

**Comment by jonathandturner** [comment]
the reason I ask is that it seems like your vscode install *isn't* able to see the RLS_ROOT environment variable.  Maybe it's not in your bash profile?

**Comment by amand1996** [comment]
how can I set that? by the root of the checkout, you mean the folder rls which we get after cloning from github?

**Comment by jonathandturner** [comment]
right, so if you check out the source, I mean the main part of that checkout, not the `src` directory part, but where the Cargo.toml is.

**Comment by amand1996** [comment]
Thanks. I gave the path to that only. What do I need to put in bash_profile?

**Comment by jonathandturner** [comment]
I mean wherever you put your environment variables so they can be seen by applications.  In my .bash_profile, I have:

```
export RLS_ROOT="/Users/jturner/Source/rls"
```

VSCode runs a new instance of the environment, so it needs to be able to pick up RLS_ROOT in the new environment.

**Comment by amand1996** [comment]
Tried this too. Still it doesn't work :(

**Comment by amand1996** [comment]
source $HOME/.cargo/env

What does the above statement do? how shall i insert it into the .profile? every time when i open a new terminal window, I need to enter the above command before I can use rustc.

**Comment by amand1996** [comment]
I'm using zsh? Hope thats not a problem. I had to change .zshrc for making rust commands to work on every new terminal windows. Maybe I need to export the variables to .zshrc only?

**Comment by Nashenas88** [comment]
Make sure you close ALL instances of vscode and also check your native process explorer and kill all instances of `code` before trying again. For me on Mac it was caching the environment from the first run of vscode. That one took me hours to track down.

**Comment by amand1996** [comment]
I restarted the system. Doesnt seem to work. Attaching the debug log of vscode.
[log.txt](https://github.com/jonathandturner/rls_vscode/files/856384/log.txt)

**Comment by amand1996** [comment]
which version of node and vscode shall i use? somewhere i found that some versions of node and vscode have some issues with this.

**Comment by jonathandturner** [comment]
I don't use zsh, but I'm assuming there's an equivalent you need to set up for it.  Apparently there might be a .zprofile?  You'll have to read up on your shell's docs to see how to set up environment variables.  The .bash_profile assumes you're using bash.

**Comment by jonathandturner** [comment]
As long as you're on a recent version of npm and vscode it should work.  I'm on npm 3.8.3 and vscode 1.10.2

**Comment by amand1996** [comment]
Thanks! It's working fine now. The issue was caused due to .zprofile. I had to put the path variables in .zprofile for zsh.

**Comment by golddranks** [comment]
I was having the same problem, and fixing $RLS_ROOT (it contained `~/.../rls` instead of `/Users/user/.../rls`)

Maybe it could catch and notify if it can't find rls?

**Comment by sethlopezme** [comment]
Sorry to raise this issue from the dead, but I am also experiencing this. I normally use vscode-rust, which runs RLS successfully, but I am trying to get this extension to work so I can compare it with vscode-rust for debugging purposes.

VS Code 1.11.2
node 7.9.0
macOS 10.12.4

To use this extension, I first disabled vscode-rust. Next, I pulled the master branch down for rls_vscode, ran `npm install`, and used the debugger to launch a new window with the extension running. At that time, I saw the following error:

```
Uncaught Exception:  Error: spawn rls ENOENT
Error: spawn rls ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.global.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I have rls installed through rustup, so I assume I shouldn't need to have an `RLS_ROOT` environment variable set or anything. Am I doing something incorrectly?

**Comment by jonathandturner** [comment]
@sethlopezme - rls_vscode should run rls itself, you shouldn't have to run it from the commandline.

Hmmm, and you installed `rls` via `rustup`?  If so, you may want to try a more recent version of rls_vscode, as it now runs rls through rustup.

**Comment by sethlopezme** [comment]
It's not an issue anymore. I'm the one who made the PR to make rls_vscode use rustup to start RLS. No worries, now!

**Comment by jonathandturner** [comment]
Ahh, right!  Thanks again 😄
