### ISSUE TITLE
VS Code + RLS doesn't work properly on workspaces

### ISSUE THREAD

**Issue by staktrace** [jonathandturner/rls_vscode#43]
I followed the instructions at https://github.com/rust-lang-nursery/rls to set up VS code and RLS. I wanted to use it to navigate the `servo/webrender` repository. This repository contains a workspace Cargo.toml at the root and then a bunch of crates inside. If I open the root folder (with the workspace Cargo.toml) in VS Code, it seems to not do all the proper analysis, and doesn't find some things (a specific example is finding all references to the scroll function in webrender/src/clip_scroll_node.rs). However if I open the webrender crate folder, it works fine. It would be great if it worked with the workspace and could do analysis across both webrender and webrender_traits.

**Comment by nrc** [comment]
dup of https://github.com/rust-lang-nursery/rls/issues/132
