### ISSUE TITLE
Trouble Making RLS a default extension

### ISSUE THREAD

**Issue by alex-ozdemir** [jonathandturner/rls_vscode#46]
I've gotten the extension working when I start VSCode in the `rls_vscode` directory, but can't get it working as a default extension.

That is, when I start the extension I get an error: `Couldn't start client Rust Language Server`.

My link situation:

```
aozdemir@principia ~/.vscode/extensions $ ls -l
total 20K
drwxr-xr-x 4 aozdemir aozdemir 4.0K Apr  4 00:01 AndrsDC.base16-themes-1.1.2/
drwxr-xr-x 7 aozdemir aozdemir 4.0K Apr  3 23:52 ms-vscode.cpptools-0.10.5/
lrwxrwxrwx 1 aozdemir aozdemir   30 Apr 12 09:27 rls_vscode -> /home/aozdemir/code/rls_vscode/
drwxr-xr-x 5 aozdemir aozdemir 4.0K Apr 12 13:51 vscodevim.vim-0.6.15/
```

But I can start the extension via debug mode just fine, and it works:
```
aozdemir@principia ~/.vscode/extensions $ cd /home/aozdemir/code/rls_vscode
aozdemir@principia ~/code/rls_vscode $ code .
```

This latter approach does generate a warning though: `[/home/aozdemir/code/rls_vscode]: Overwriting extension /home/aozdemir/.vscode/extensions/rls_vscode with /home/aozdemir/code/rls_vscode.`

Any idea what I'm doing wrong?

**Comment by alex-ozdemir** [comment]
Ah, the output from the extension includes the following:

```
Launching server using command rls failed.
```

**Comment by martinlindhe** [comment]
@alex-ozdemir Beginning yesterday, rls can now be installed with rustup, making the setup easier for everyone.

Assuming you are using rustup, please give this a try:

```
rustup default nightly
rustup update nightly
rustup component add rls
rustup component add rust-analysis
rustup component add rust-src
```

now, rustup will keep your rls up-to-date too!
More info: http://www.jonathanturner.org/2017/04/rls-now-in-nightly.md.html

**Comment by alex-ozdemir** [comment]
Ah yes, the installation mechanism has changed.
Thanks!
