### ISSUE TITLE
Spawn RLS child process with rustup

### ISSUE THREAD

**Issue by sethlopezme** [jonathandturner/rls_vscode#52]
When the `RLS_ROOT` environment variable isn't present, the extension attempts to start RLS by spawning a child process with the command `rls`. If we follow the instructions in the README, we should have installed RLS with rustup, which means that the child process should be using the command `rustup` with the arguments `["run", "nightly", "rls"]`.

**Comment by jonathandturner** [comment]
Interested in sending a PR for this?  Should be a pretty easy fix.
