### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [jonathandturner/rls_vscode#55]
I've done all the steps from readme.md and I got the following after trying to start debugging:

![image](https://cloud.githubusercontent.com/assets/873919/25778545/a662d1aa-3309-11e7-8696-073be3198021.png)

**Comment by jonathandturner** [comment]
Technically, since these are TypeScript errors you can ignore them.

Still, I'm curious why they're occurring. It seems like some of the TS definitions might have gotten out of sync.  Will take a look to see if I can repro it.

**Comment by jonathandturner** [comment]
Looking at this bug again, it looks like you're following the old steps?  The current steps no longer open the project and try to run debug from inside of vscode.

**Comment by vasily-kirichenko** [comment]
readme.md reads
> Next, without installing the client as a regular VSCode extension, open the client folder in VSCode. Go to the debugger and run "Launch Extension". This opens a new instance of VSCode with the plugin installed.

what's the recommended way then?..

**Comment by nrc** [comment]
> what's the recommended way then?..

This is the recommended way, perhaps it would be better phrased as

> Next (without installing the client as a regular VSCode extension), open the client folder in VSCode. Go to the debugger and run "Launch Extension". This opens a new instance of VSCode with the plugin installed.
