### ISSUE TITLE
Argument of type "rustDocument/diagnosticsBegin" is not assignable to parameter of type 'NotificationType<{}>.

### ISSUE THREAD

**Issue by jaxx** [jonathandturner/rls_vscode#60]
Today I updated rls and rls_vscode and got this error. Anybody got idea how to fix this?

![screenshot at 2017-06-08 09-05-22](https://user-images.githubusercontent.com/723258/26914405-a8ab1c36-4c29-11e7-875f-b62184f26c89.png)

**Comment by nrc** [comment]
@Xanewok any ideas?

@jaxx you could try updating the npm modules (I think `npm install`)

**Comment by Xanewok** [comment]
Yes, it requires `npm install`, since vscode-languageclient changed API slightly since 3.x.

**Comment by jaxx** [comment]
Aah, thanks! Update worked,
