### ISSUE TITLE
Nothing works on windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [jonathandturner/rls_vscode#9]
![image](https://cloud.githubusercontent.com/assets/873919/19516710/ee728194-9605-11e6-85d7-75776818b22d.png)

`rls` process is running.

**Comment by Arnavion** [comment]
Yes, the LS client doesn't work. The VFS can't find any files.

I noticed textDocument/didOpen is currently not implemented. Not sure if that's the reason or something else.

If you try the HTTP client, hover still may not work (in my sample program all the types are returned as empty string), but GoToDefinition appears to work.

**Comment by masaeedu** [comment]
@Arnavion Now that jonathandturner/rls#54 is resolved, would this work as well?

**Comment by jonathandturner** [comment]
@masaeedu - yes, this should also work.  Closing.
